# Generated by Django 4.1.2 on 2022-10-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantsModel',
            fields=[
                ('aspirant_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_Name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, null=True)),
                ('phone_Number', models.BigIntegerField()),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('education', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('pin_number', models.CharField(max_length=255)),
                ('register_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'Aspirants_Details',
            },
        ),
        migrations.CreateModel(
            name='AspirantFeadbackModel',
            fields=[
                ('feadback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_message', models.TextField()),
                ('feedback_sentiment', models.CharField(max_length=20)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('rating', models.CharField(max_length=10, null=True)),
                ('aspirant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirantapp.aspirantsmodel')),
            ],
            options={
                'db_table': 'aspirant_feadback',
            },
        ),
    ]
