# Generated by Django 4.1.2 on 2022-10-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirantapp', '0002_remove_aspirantfeadbackmodel_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantfeadbackmodel',
            name='rating2',
            field=models.IntegerField(help_text='b', null=True),
        ),
        migrations.AddField(
            model_name='aspirantfeadbackmodel',
            name='rating3',
            field=models.IntegerField(help_text='c', null=True),
        ),
        migrations.AlterField(
            model_name='aspirantfeadbackmodel',
            name='rating1',
            field=models.IntegerField(help_text='a', null=True),
        ),
    ]
