# Generated by Django 4.1.2 on 2022-10-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirantapp', '0003_aspirantfeadbackmodel_rating2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirantfeadbackmodel',
            name='rating1',
            field=models.IntegerField(help_text='rating1', null=True),
        ),
        migrations.AlterField(
            model_name='aspirantfeadbackmodel',
            name='rating2',
            field=models.IntegerField(help_text='rating2', null=True),
        ),
        migrations.AlterField(
            model_name='aspirantfeadbackmodel',
            name='rating3',
            field=models.IntegerField(help_text='rating3', null=True),
        ),
    ]
