# Generated by Django 4.1.2 on 2022-10-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirantapp', '0004_alter_aspirantfeadbackmodel_rating1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirantfeadbackmodel',
            name='rating1',
            field=models.IntegerField(help_text='How do you rate for Study materiala', null=True),
        ),
    ]
