# Generated by Django 4.1.2 on 2022-10-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirantapp', '0005_alter_aspirantfeadbackmodel_rating1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirantfeadbackmodel',
            name='rating1',
            field=models.IntegerField(help_text='a', null=True),
        ),
    ]
