# Generated by Django 4.1.2 on 2022-10-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_upscinterviewvideos_videos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upscmocktest',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
